services:
  accounts:
    image: "hmhetre/accounts:v1"
    container_name: accounts-ms
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - my_bank

  loans:
    image: "hmhetre/loans:v1"
    container_name: loans-ms
    ports:
      - "9091:9091"
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - my_bank

  cards:
    image: "hmhetre/cards:v1"
    container_name: cards-ms
    ports:
      - "9092:9092"
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - my_bank

networks:
  my_bank:
    driver: "bridge"
