server:
  port: 9091

spring:
  application:
    name: loans

  datasource:
    url: jdbc:h2:mem:loanDB
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:
      - "application-qa.yaml"
      - "application-prod.yaml"

build:
  version: "1.0"


loans:
  message: "Welcome to bank loans related local APIs"
  contactDetails:
    name: Hari Mhetre
    email: hari.mhetre22@gmail.com
  onCallSupport:
    - (555) 555-1234
    - (444) 444-1234