services:
  network-deploy-service:
    networks:
      - my-bank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  microservice-gatewayserver-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:9093/"
      SPRING_PROFILES_ACTIVE: "qa"
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
