server:
  port: 9090
spring:
  application:
    name: accounts
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://configserver:9093/"
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
#  cloud:
#    bus:
#      enabled: false
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  info:
    env:
      enabled: true

  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

build:
  version: "1.0"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:9094/eureka/

info:
  app:
    name: "Account"
    description: "This is my bank cards microservice"
    version: "1.0.0"

logging:
  level:
    com:
      bank:
        accounts: Debug