spring:
  application:
    name: "configServer"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
         git:
           uri: "https://github.com/harimhetre/bank-microservices-config.git"
           default-label: dev
           timeout: 5
           force-pull: true
           clone-on-start: true
    rabbitmq:
      host: rabbit
      port: 5672
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8"

server:
  port: 9093