spring:
  application:
    name: "configServer"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
         git:
           uri: "https://github.com/harimhetre/bank-microservices-config.git"
           default-label: dev
           timeout: 5
           force-pull: true
           clone-on-start: true

server:
  port: 9093